{
 "title": "telegraf",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "host",
    "query": "select distinct host from telegraf_cpu where $__timeFilter(timestamp)"
   },
   {
    "name": "net_interface",
    "query": "select distinct interface from telegraf_net where host = '$host' and $__timeFilter(timestamp)"
   },
   {
    "name": "disk_path",
    "query": "select distinct path from telegraf_disk where host = '$host' and $__timeFilter(timestamp)"
   },
   {
    "name": "diskio_name",
    "query": "select distinct name from telegraf_diskio where host = '$host' and $__timeFilter(timestamp)"
   },
   {
    "name": "docker_container_name",
    "query": "select distinct container_name from telegraf_docker_container_cpu where host = '$host' and $__timeFilter(timestamp)"
   },
   {
    "name": "nvidia_name",
    "query": "select distinct name from telegraf_nvidia_smi where host = '$host' and $__timeFilter(timestamp)"
   }
  ]
 },
 "panels": [
  { "title": "stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "load1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    cast(0 as timestamp) as time,\n    round(last(load1), 2) as load1\nfrom\n    telegraf_system\nwhere\n    host = '$host'\n    and load1 is not null\n    and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "load5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    cast(0 as timestamp) as time,\n    round(last(load5), 2) as load5\nfrom\n    telegraf_system\nwhere\n    host = '$host'\n    and load5 is not null\n    and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "load15",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    cast(0 as timestamp) as time,\n    round(last(load15), 2) as load15\nfrom\n    telegraf_system\nwhere\n    host = '$host'\n    and load5 is not null\n    and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    cast(0 as timestamp) as time,\n    last(uptime) as uptime\nfrom\n    telegraf_system\nwhere\n    host = '$host'\n    and uptime is not null\n    and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "sensors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  cast(0 as timestamp) as time,\n  max(temp_input) as temp_input\nfrom (\n    select\n      last(temp_input) as temp_input,\n      concat(chip, '-', feature) as metric\n    from\n      telegraf_sensors\n    where\n      host = '$host'\n      and temp_input is not null\n      and temp_input > 0\n      and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  { "title": "sys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\n    $__time(timestamp),\n    avg(usage_active) as cpu_usage_active\nfrom\n    telegraf_cpu\nwhere\n    host = '$host'\n    and cpu = 'cpu-total'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "with\n  telegraf_linux_cpu2 as ((\n    select\n      timestamp,\n      sum(throttle_total_time) as throttle_total_time\n    from telegraf_linux_cpu\n    where\n      host = '$host'\n      and $__timeFilter(timestamp)\n  ) timestamp(timestamp))\nselect\n  $__time(timestamp),\n  throttle_time_ms*1.0/(diff_seconds*1000.0)*100.0 as throttle_percentage\nfrom (\n  select\n    timestamp,\n    sum(throttle_time_ms) as throttle_time_ms,\n    sum(diff_seconds) as diff_seconds\n  from (\n    select\n      t1.timestamp, \n      (case when t1.throttle_total_time >= t2.throttle_total_time then t1.throttle_total_time-t2.throttle_total_time else null end) as throttle_time_ms,\n      datediff('s', t1.timestamp, t2.timestamp) as diff_seconds\n    from telegraf_linux_cpu2 t1 \n    lt join telegraf_linux_cpu2 t2\n  )\n  sample by $__interval fill(null)\n)\n"
    }
   ]
  },
  {
   "title": "mem&swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\n    $__time(timestamp),\n    avg(used_percent) as mem_used_percent\nfrom\n    telegraf_mem\nwhere\n    host = '$host'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select\n    $__time(timestamp),\n    100.0-avg(available_percent) as mem_notavailable_percent\nfrom\n    telegraf_mem\nwhere\n    host = '$host'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select\n    $__time(timestamp),\n    avg(used_percent) as swap_used_percent\nfrom\n    telegraf_swap\nwhere\n    host = '$host'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select\n  $__time(timestamp),\n  max(temp_input) as max_temp_input\nfrom (\n    select\n      timestamp,\n      avg(temp_input) as temp_input,\n      concat(chip, '-', feature) as metric\n    from\n      telegraf_sensors\n    where\n      host = '$host'\n      and temp_input is not null\n      and temp_input > 0\n      and $__timeFilter(timestamp)\n    sample by $__interval fill(null)\n)"
    },
    {
     "rawSql": "select\n    $__time(timestamp),\n    avg(temp_input) as value,\n    concat(chip, '-', feature) as metric\nfrom\n    telegraf_sensors\nwhere\n    host = '$host'\n    and temp_input is not null\n    and temp_input > 0\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)\n"
    }
   ]
  },
  {
   "title": "net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "net",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "rawSql": "with\n  telegraf_net2 as (\n    select timestamp, bytes_recv, bytes_sent, packets_recv, packets_sent\n    from telegraf_net\n    where\n      host = '$host'\n      and interface = '$net_interface'\n      and $__timeFilter(timestamp)\n  )\nselect\n  time,\n  bytes_recv*1.0/diff_seconds as bytes_recv_rate,\n  bytes_sent*1.0/diff_seconds as bytes_sent_rate,\n  packets_recv*1.0/diff_seconds as packets_recv_rate,\n  packets_sent*1.0/diff_seconds as packets_sent_rate\nfrom (\n  select\n    $__time(timestamp),\n    sum(bytes_recv) as bytes_recv,\n    sum(bytes_sent) as bytes_sent,\n    sum(packets_recv) as packets_recv,\n    sum(packets_sent) as packets_sent,\n    sum(diff_seconds) as diff_seconds\n  from (\n    select\n      t1.timestamp, \n      (case when t1.bytes_recv >= t2.bytes_recv then t1.bytes_recv-t2.bytes_recv else null end) as bytes_recv,\n      (case when t1.bytes_sent >= t2.bytes_sent then t1.bytes_sent-t2.bytes_sent else null end) as bytes_sent,\n      (case when t1.packets_recv >= t2.packets_recv then t1.packets_recv-t2.packets_recv else null end) as packets_recv,\n      (case when t1.packets_sent >= t2.packets_sent then t1.packets_sent-t2.packets_sent else null end) as packets_sent,\n      datediff('s', t1.timestamp, t2.timestamp) as diff_seconds\n    from telegraf_net2 t1\n    lt join telegraf_net2 t2\n  )\n  sample by $__interval fill(null)\n)"
      }
     ]
    },
    {
     "title": "netstat",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(tcp_established) as tcp_established,\n    avg(tcp_syn_sent) as tcp_syn_sent,\n    avg(tcp_syn_recv) as tcp_syn_recv,\n    avg(tcp_fin_wait1) as tcp_fin_wait1,\n    avg(tcp_fin_wait2) as tcp_fin_wait2,\n    avg(tcp_time_wait) as tcp_time_wait,\n    avg(tcp_close) as tcp_close,\n    avg(tcp_close_wait) as tcp_close_wait,\n    avg(tcp_last_ack) as tcp_last_ack,\n    avg(tcp_listen) as tcp_listen,\n    avg(tcp_closing) as tcp_closing,\n    avg(tcp_none) as tcp_none,\n    avg(udp_socket) as udp_socket\nfrom\n    telegraf_netstat\nwhere\n    host = '$host'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk",
     "type": "timeseries",
     "description": "(by disk_path)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select \n  time,\n  used_percent as space_used_percent,\n  (inodes_used*1.0/inodes_total*100) as inodes_used_percent\nfrom (\n  select\n    $__time(timestamp),\n    max(used_percent) as used_percent,\n    avg(inodes_used) as inodes_used,\n    avg(inodes_total) as inodes_total,\n    path\n  from\n    telegraf_disk\n  where\n    host = '$host'\n    and path = '$disk_path'\n    and $__timeFilter(timestamp)\n  sample by $__interval fill(null)\n)"
      }
     ]
    },
    {
     "title": "diskio (bytes)",
     "type": "timeseries",
     "description": "(by diskio_name)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "rawSql": "with\n  telegraf_diskio2 as (\n    select timestamp, read_bytes, write_bytes\n    from telegraf_diskio\n    where\n      host = '$host'\n      and name = '$diskio_name'\n      and $__timeFilter(timestamp)\n  )\nselect\n  time,\n  read_bytes*1.0/diff_seconds as read_bytes_rate,\n  write_bytes*1.0/diff_seconds as write_bytes_rate\nfrom (\n  select\n    $__time(timestamp),\n    sum(read_bytes) as read_bytes,\n    sum(write_bytes) as write_bytes,\n    sum(diff_seconds) as diff_seconds\n  from (\n      select\n          t1.timestamp, \n          (case when t1.read_bytes >= t2.read_bytes then t1.read_bytes-t2.read_bytes else null end) as read_bytes,\n          (case when t1.write_bytes >= t2.write_bytes then t1.write_bytes-t2.write_bytes else null end) as write_bytes,\n          datediff('s', t1.timestamp, t2.timestamp) as diff_seconds\n      from telegraf_diskio2 t1\n      lt join telegraf_diskio2 t2\n  )\n  sample by $__interval fill(null)\n)"
      }
     ]
    },
    {
     "title": "diskio (io) ",
     "type": "timeseries",
     "description": "(by diskio_name)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "with\n  telegraf_diskio2 as (\n    select timestamp, io_time, weighted_io_time\n    from telegraf_diskio\n    where\n      host = '$host'\n      and name = '$diskio_name'\n      and $__timeFilter(timestamp)\n  )\nselect\n  time,\n  io_time*1.0/(diff_seconds*1000)*100 as io_utilization_percent,\n  weighted_io_time*1.0/(diff_seconds*1000) as average_queue_depth\nfrom (\n  select\n    $__time(timestamp),\n    sum(io_time) as io_time,\n    sum(weighted_io_time) as weighted_io_time,\n    sum(diff_seconds) as diff_seconds\n  from (\n    select\n        t1.timestamp, \n        (case when t1.io_time >= t2.io_time then t1.io_time-t2.io_time else null end) as io_time,\n        (case when t1.weighted_io_time >= t2.weighted_io_time then t1.weighted_io_time-t2.weighted_io_time else null end) as weighted_io_time,\n        datediff('s', t1.timestamp, t2.timestamp) as diff_seconds\n    from telegraf_diskio2 t1\n    lt join telegraf_diskio2 t2\n  )\n  sample by $__interval fill(null)\n)"
      },
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(iops_in_progress) as iops_in_progress\nfrom\n    telegraf_diskio\nwhere\n    host = '$host'\n    and name = '$diskio_name'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "docker_cpu",
     "type": "timeseries",
     "description": "(by docker_container_name)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(usage_percent) as usage_percent\nfrom\n    telegraf_docker_container_cpu\nwhere\n    host = '$host'\n    and container_name = '$docker_container_name'\n    and cpu = 'cpu-total'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    },
    {
     "title": "docker_mem",
     "type": "timeseries",
     "description": "(by docker_container_name)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select \n  time,\n  (usage*1.0/limit*100) as usage_percent\nfrom (\n  select\n    $__time(timestamp),\n    avg(usage) as usage,\n    avg(limit) as limit\n  from\n    telegraf_docker_container_mem\n  where\n    host = '$host'\n    and container_name = '$docker_container_name'\n    and $__timeFilter(timestamp)\n  sample by $__interval fill(null)\n)"
      }
     ]
    },
    {
     "title": "docker_net",
     "type": "timeseries",
     "description": "(by docker_container_name)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "rawSql": "with\n  telegraf_docker_container_net2 as (\n    select timestamp, rx_bytes, tx_bytes, tx_packets, rx_packets\n    from telegraf_docker_container_net\n    where\n      host = '$host'\n      and container_name = '$docker_container_name'\n      and $__timeFilter(timestamp)\n  )\nselect\n  time,\n  rx_bytes*1.0/diff_seconds as rx_bytes_rate,\n  tx_bytes*1.0/diff_seconds as tx_bytes_rate,\n  tx_packets*1.0/diff_seconds as tx_packets_rate,\n  rx_packets*1.0/diff_seconds as rx_packets_rate\nfrom (\n  select\n    $__time(timestamp),\n    sum(rx_bytes) as rx_bytes,\n    sum(tx_bytes) as tx_bytes,\n    sum(tx_packets) as tx_packets,\n    sum(rx_packets) as rx_packets,\n    sum(diff_seconds) as diff_seconds\n  from (\n      select\n          t1.timestamp, \n          (case when t1.rx_bytes >= t2.rx_bytes then t1.rx_bytes-t2.rx_bytes else null end) as rx_bytes,\n          (case when t1.tx_bytes >= t2.tx_bytes then t1.tx_bytes-t2.tx_bytes else null end) as tx_bytes,\n          (case when t1.tx_packets >= t2.tx_packets then t1.tx_packets-t2.tx_packets else null end) as tx_packets,\n          (case when t1.rx_packets >= t2.rx_packets then t1.rx_packets-t2.rx_packets else null end) as rx_packets,\n          datediff('s', t1.timestamp, t2.timestamp) as diff_seconds\n      from telegraf_docker_container_net2 t1\n      lt join telegraf_docker_container_net2 t2\n  )\n  sample by $__interval fill(null)\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "nvidia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "power",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(power_draw) as power_draw\nfrom\n    telegraf_nvidia_smi\nwhere\n    host = '$host'\n    and name = '$nvidia_name'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    },
    {
     "title": "utilizations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(utilization_gpu) as utilization_gpu,\n    avg(utilization_memory) as utilization_memory,\n    avg(utilization_encoder) as utilization_encoder,\n    avg(utilization_decoder) as utilization_decoder\nfrom\n    telegraf_nvidia_smi\nwhere\n    host = '$host'\n    and name = '$nvidia_name'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    },
    {
     "title": "sensors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "select\n    $__time(timestamp),\n    avg(temperature_gpu) as temperature_gpu\nfrom\n    telegraf_nvidia_smi\nwhere\n    host = '$host'\n    and name = '$nvidia_name'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
      }
     ]
    }
   ]
  }
 ]
}